version: '3.1'

services:
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: zookeeper:3.4
    restart: on-failure
    volumes:
      - "./zookeeper/data:/data"
      - "./zookeeper/logs:/datalog"
    ports:
      - "2181:2181"
      - "2182:2182"

  clickhouse:
    image: yandex/clickhouse-server:21.3.20
    hostname: clickhouse-01
    container_name: clickhouse-01
    ports:
      - "9001:9000"
      - "8123:8123"
    volumes:
      - ./clickhouse/clickhouse_config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
      - ./clickhouse/macros.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - "zookeeper"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:1.0.0
    restart: on-failure
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kdata:/kdata
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=${EXPOSED_HOSTNAME}:2181
      - KAFKA_ADVERTISED_HOST_NAME=${EXPOSED_HOSTNAME}
      - JMX_PORT=9093
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_DELETE_TOPIC_ENABLE=true
      - KAFKA_LOG_RETENTION_HOURS=1
      - KAFKA_MESSAGE_MAX_BYTES=10000000
      - KAFKA_REPLICA_FETCH_MAX_BYTES=10000000
      - KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS=60000
      - KAFKA_NUM_PARTITIONS=2
      - KAFKA_DELETE_RETENTION_MS=1000
    ports:
      - "9092:9092"
      - "9093:9093"

  kafka-manager:
    container_name: kafka-manager
    image: hlebalbau/kafka-manager:1.3.3.16
    restart: on-failure
    depends_on:
      - kafka
      - zookeeper
    command: -Dconfig.file=/kafka-manager/conf/application.conf -Dapplication.home=/kafkamanager
    environment:
      - ZK_HOSTS=${EXPOSED_HOSTNAME}
      - APPLICATION_SECRET=letmein
    ports:
      - "9000:9000"
