apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: default
      port: 9001
      server: innerip
      username: default
      tlsSkipVerify: false
    secureJsonData:
      password: